# This file contains all available configuration options with their default values.

# options for analysis running
run:
  # default concurrency is a available CPU number
  concurrency: 4

  # timeout for analysis, e.g. 30s, 5m, default is 1m

  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1

# output configuration options
output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"

  # print lines of code with issue, default is true
  print-issued-lines: true

  # print linter name in the end of issue text, default is true
  print-linter-name: true


# all available settings of specific linters
linters-settings:
  goimports:
    local-prefixes: server
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 15
  dupl:
    # tokens count to trigger issue, 150 by default
    threshold: 150
  lll:
    line-length: 140
  depguard:
    rules:
      main:
        list-mode: lax
        files:
          - $all
        allow:
          - $gostd
        deny:
          - pkg: "github.com/pkg/errors"
            desc: Should be replaced by standard lib errors package

linters:
  enable:
    - govet
    - errcheck
    - ineffassign
    - typecheck
    - bodyclose
    - gosimple
    - staticcheck
    - unused
    - revive
    - stylecheck
    - gosec
    - unconvert
    - goconst
    - gocyclo
    - gocognit
    - asciicheck
    - gofmt
    - goimports
    - gomodguard
    - misspell
    - unparam
    - dogsled
    - nakedret
    - prealloc
    - gocritic
    - gochecknoglobals
    - whitespace
    - wsl
    - goprintffuncname
    - testpackage
    - nolintlint
    - noctx
    - dupl
    - goheader
    - depguard
    - exhaustive
    - mnd
    - nestif
    - predeclared
    - testpackage
    - nolintlint
    - noctx
    - tparallel
    - makezero
  fast: false
  disable-all: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - gochecknoglobals
        - wsl
        - funlen
        - goerr113
    - text: "Errors unhandled"
      linters:
        - gosec
    - linters:
        - lll
      source: "^//go:generate "