// Code generated by MockGen. DO NOT EDIT.
// Source: client/internal/infrastructure/client (interfaces: ConnectionReaderWriter)

// Package mock is a generated GoMock package.
package mock

import (
	net "net"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockConnectionReaderWriter is a mock of ConnectionReaderWriter interface.
type MockConnectionReaderWriter struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionReaderWriterMockRecorder
}

// MockConnectionReaderWriterMockRecorder is the mock recorder for MockConnectionReaderWriter.
type MockConnectionReaderWriterMockRecorder struct {
	mock *MockConnectionReaderWriter
}

// NewMockConnectionReaderWriter creates a new mock instance.
func NewMockConnectionReaderWriter(ctrl *gomock.Controller) *MockConnectionReaderWriter {
	mock := &MockConnectionReaderWriter{ctrl: ctrl}
	mock.recorder = &MockConnectionReaderWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectionReaderWriter) EXPECT() *MockConnectionReaderWriterMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *MockConnectionReaderWriter) Read(arg0 net.Conn) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockConnectionReaderWriterMockRecorder) Read(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockConnectionReaderWriter)(nil).Read), arg0)
}

// Write mocks base method.
func (m *MockConnectionReaderWriter) Write(arg0 net.Conn, arg1 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockConnectionReaderWriterMockRecorder) Write(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockConnectionReaderWriter)(nil).Write), arg0, arg1)
}
